import type {
  CaseLibraryRecord,
  CaseLibrarySummaryStats,
  CaseLibraryActivityItem,
  CaseLibraryMetrics,
} from './types';

// ─── Cases ────────────────────────────────────────────────────────────────────

export const MOCK_CASES: CaseLibraryRecord[] = [
  {
    caseId: 'CASE-2026-0412-001', title: 'Euler Finance Bridge Drain',
    summary: 'Exploiter used flash loan to drain $197M via donate() vulnerability in Euler lending bridge.',
    type: 'Bridge Exploit', source: 'SlowMist', chainSystem: 'Ethereum',
    severity: 'critical', status: 'verified', replayStatus: 'passed', doctrineStatus: 'linked',
    cveCount: 2, cveRefs: ['CVE-2026-10341', 'CVE-2026-10342'],
    ingestedAt: '2026-04-12T08:14:00Z', updatedAt: '2026-04-14T11:02:00Z',
    tags: ['flash-loan', 'bridge', 'lending'], confidence: 98,
  },
  {
    caseId: 'CASE-2026-0411-002', title: 'Chainlink Staleness — USDC/ETH',
    summary: 'Oracle answer returned stale price during network congestion window; liquidation threshold triggered incorrectly.',
    type: 'Oracle Manipulation', source: 'ImmuneFi', chainSystem: 'Ethereum',
    severity: 'high', status: 'doctrine_tagged', replayStatus: 'available', doctrineStatus: 'updated',
    cveCount: 1, cveRefs: ['CVE-2026-10198'],
    ingestedAt: '2026-04-11T14:30:00Z', updatedAt: '2026-04-13T09:15:00Z',
    tags: ['oracle', 'staleness', 'liquidation'], confidence: 94,
  },
  {
    caseId: 'CASE-2026-0410-003', title: 'Compound Governance Param Exploit',
    summary: 'Attacker accumulated governance tokens via flash loan, passed malicious proposal modifying collateral factors.',
    type: 'Governance Exploit', source: 'ImmuneFi', chainSystem: 'Ethereum',
    severity: 'critical', status: 'replay_ready', replayStatus: 'available', doctrineStatus: 'linked',
    cveCount: 3, cveRefs: ['CVE-2026-10055', 'CVE-2026-10056', 'CVE-2026-10057'],
    ingestedAt: '2026-04-10T07:55:00Z', updatedAt: '2026-04-12T16:40:00Z',
    tags: ['governance', 'flash-loan', 'proposal'], confidence: 97,
  },
  {
    caseId: 'CASE-2026-0409-004', title: 'Solana Keeper Network Outage',
    summary: 'Keeper bots failed to process liquidations during validator downtime; 14% of positions went under-collateralised.',
    type: 'Keeper Failure', source: 'Manual', chainSystem: 'Solana',
    severity: 'high', status: 'normalized', replayStatus: 'pending', doctrineStatus: 'pending',
    cveCount: 0, ingestedAt: '2026-04-09T21:10:00Z', updatedAt: '2026-04-10T08:30:00Z',
    tags: ['keeper', 'liquidation', 'downtime'], confidence: 88,
  },
  {
    caseId: 'CASE-2026-0408-005', title: 'USDC Reserve Liquidity Imbalance',
    summary: 'Cross-chain reserve rebalancing lag created a 3h window where USDC redemptions exceeded available liquidity.',
    type: 'Treasury Imbalance', source: 'Research', chainSystem: 'Multi',
    severity: 'high', status: 'classified', replayStatus: 'missing', doctrineStatus: 'pending',
    cveCount: 0, ingestedAt: '2026-04-08T18:00:00Z', updatedAt: '2026-04-09T12:00:00Z',
    tags: ['stablecoin', 'liquidity', 'cross-chain'], confidence: 82,
  },
  {
    caseId: 'CASE-2026-0407-006', title: 'UST/Luna Terminal Depeg Sequence',
    summary: 'Death spiral initiated by coordinated redemption pressure; algorithmic peg mechanism exhausted reserve within 72h.',
    type: 'Stablecoin Depeg', source: 'SlowMist', chainSystem: 'Terra',
    severity: 'critical', status: 'verified', replayStatus: 'passed', doctrineStatus: 'linked',
    cveCount: 4, cveRefs: ['CVE-2026-9910', 'CVE-2026-9911', 'CVE-2026-9912', 'CVE-2026-9913'],
    ingestedAt: '2026-04-07T06:45:00Z', updatedAt: '2026-04-10T14:20:00Z',
    tags: ['stablecoin', 'depeg', 'algorithmic'], confidence: 100,
  },
  {
    caseId: 'CASE-2026-0407-007', title: 'Arbitrum Sequencer Downtime',
    summary: '2h sequencer outage caused pending transactions to expire; DeFi protocols paused operations automatically.',
    type: 'Chain Halt', source: 'Manual', chainSystem: 'Arbitrum',
    severity: 'medium', status: 'doctrine_tagged', replayStatus: 'passed', doctrineStatus: 'linked',
    cveCount: 0, ingestedAt: '2026-04-07T11:30:00Z', updatedAt: '2026-04-08T09:00:00Z',
    tags: ['sequencer', 'L2', 'downtime'], confidence: 99,
  },
  {
    caseId: 'CASE-2026-0406-008', title: 'Aave Risk Param Misconfiguration',
    summary: 'Governance proposal lowered LTV threshold for volatile collateral without adjusting liquidation bonus; under-collateralised positions accumulated.',
    type: 'Config Drift', source: 'Research', chainSystem: 'Ethereum',
    severity: 'medium', status: 'needs_review', replayStatus: 'missing', doctrineStatus: 'none',
    cveCount: 1, cveRefs: ['CVE-2026-9800'],
    ingestedAt: '2026-04-06T15:20:00Z', updatedAt: '2026-04-06T15:20:00Z',
    tags: ['config', 'governance', 'LTV'], confidence: 76,
  },
  {
    caseId: 'CASE-2026-0405-009', title: 'SVB Settlement Contagion Signal',
    summary: 'Silicon Valley Bank failure created 48h USDC redemption freeze; protocol treasuries holding USDC faced liquidity shock.',
    type: 'Settlement Failure', source: 'Research', chainSystem: 'TradFi',
    severity: 'critical', status: 'verified', replayStatus: 'available', doctrineStatus: 'updated',
    cveCount: 0, ingestedAt: '2026-04-05T09:00:00Z', updatedAt: '2026-04-09T17:30:00Z',
    tags: ['tradfi', 'settlement', 'contagion'], confidence: 95,
  },
  {
    caseId: 'CASE-2026-0404-010', title: 'Tornado Cash Admin Key Compromise',
    summary: 'Attacker gained control of Tornado Cash governance via malicious proposal granting unlimited TORN token minting.',
    type: 'Admin Compromise', source: 'SlowMist', chainSystem: 'Ethereum',
    severity: 'critical', status: 'verified', replayStatus: 'failed', doctrineStatus: 'linked',
    cveCount: 2, cveRefs: ['CVE-2026-9701', 'CVE-2026-9702'],
    ingestedAt: '2026-04-04T12:00:00Z', updatedAt: '2026-04-07T10:10:00Z',
    tags: ['admin-key', 'governance', 'token-mint'], confidence: 100,
  },
  {
    caseId: 'CASE-2026-0403-011', title: 'Balancer Invariant Precision Loss',
    summary: 'Floating point precision error in invariant computation allowed rounding exploit yielding 0.4% excess per swap.',
    type: 'Contract Invariant', source: 'ImmuneFi', chainSystem: 'Ethereum',
    severity: 'high', status: 'replay_ready', replayStatus: 'available', doctrineStatus: 'pending',
    cveCount: 1, cveRefs: ['CVE-2026-9600'],
    ingestedAt: '2026-04-03T16:45:00Z', updatedAt: '2026-04-05T08:00:00Z',
    tags: ['invariant', 'precision', 'AMM'], confidence: 91,
  },
  {
    caseId: 'CASE-2026-0402-012', title: 'Sandwich MEV Cascade — Uniswap V3',
    summary: 'MEV searcher exploited predictable UniV3 LP positions during high-volatility period; 12 positions sandwiched in 4 blocks.',
    type: 'MEV Attack', source: 'Research', chainSystem: 'Ethereum',
    severity: 'medium', status: 'classified', replayStatus: 'pending', doctrineStatus: 'none',
    cveCount: 0, ingestedAt: '2026-04-02T22:15:00Z', updatedAt: '2026-04-03T07:00:00Z',
    tags: ['MEV', 'sandwich', 'uniswap'], confidence: 85,
  },
  {
    caseId: 'CASE-2026-0401-013', title: 'Optimism Bridge Replay Failure',
    summary: 'Message replaying from L1→L2 failed silently under high gas conditions; assets locked for 7 days.',
    type: 'Bridge Exploit', source: 'Manual', chainSystem: 'Optimism',
    severity: 'high', status: 'needs_review', replayStatus: 'failed', doctrineStatus: 'pending',
    cveCount: 1, cveRefs: ['CVE-2026-9500'],
    ingestedAt: '2026-04-01T08:30:00Z', updatedAt: '2026-04-02T14:20:00Z',
    tags: ['bridge', 'message-relay', 'L2'], confidence: 80,
  },
  {
    caseId: 'CASE-2026-0331-014', title: 'Synthetix Oracle Latency Window',
    summary: '9-second oracle latency window exploited via front-running; attacker captured $1.1M arbitrage.',
    type: 'Oracle Manipulation', source: 'SlowMist', chainSystem: 'Ethereum',
    severity: 'medium', status: 'doctrine_tagged', replayStatus: 'passed', doctrineStatus: 'linked',
    cveCount: 1, cveRefs: ['CVE-2026-9400'],
    ingestedAt: '2026-03-31T14:00:00Z', updatedAt: '2026-04-01T09:30:00Z',
    tags: ['oracle', 'front-run', 'latency'], confidence: 93,
  },
  {
    caseId: 'CASE-2026-0330-015', title: 'Maker Governance Flash Loan',
    summary: 'Flash loan attack accumulated 51% of governance weight for a single block, passing collateral ratio changes.',
    type: 'Governance Exploit', source: 'ImmuneFi', chainSystem: 'Ethereum',
    severity: 'critical', status: 'verified', replayStatus: 'passed', doctrineStatus: 'updated',
    cveCount: 3, cveRefs: ['CVE-2026-9301', 'CVE-2026-9302', 'CVE-2026-9303'],
    ingestedAt: '2026-03-30T10:20:00Z', updatedAt: '2026-04-03T16:00:00Z',
    tags: ['governance', 'flash-loan', 'maker'], confidence: 99,
  },
  {
    caseId: 'CASE-2026-0329-016', title: 'BNB Chain Halt — Consensus Bug',
    summary: 'Consensus-layer bug caused 30min halt; cross-chain bridges paused withdrawals pending chain re-org resolution.',
    type: 'Chain Halt', source: 'Research', chainSystem: 'BNB',
    severity: 'critical', status: 'verified', replayStatus: 'available', doctrineStatus: 'linked',
    cveCount: 0, ingestedAt: '2026-03-29T07:45:00Z', updatedAt: '2026-04-01T11:00:00Z',
    tags: ['consensus', 'chain-halt', 'bridge-pause'], confidence: 100,
  },
  {
    caseId: 'CASE-2026-0328-017', title: 'Curve Treasury LP Drain',
    summary: 'Re-entrancy in vyper compiler version 0.2.15 allowed attacker to drain stableswap pools.',
    type: 'Treasury Imbalance', source: 'SlowMist', chainSystem: 'Ethereum',
    severity: 'high', status: 'replay_ready', replayStatus: 'available', doctrineStatus: 'pending',
    cveCount: 2, cveRefs: ['CVE-2026-9200', 'CVE-2026-9201'],
    ingestedAt: '2026-03-28T19:30:00Z', updatedAt: '2026-03-30T08:45:00Z',
    tags: ['reentrancy', 'vyper', 'stableswap'], confidence: 97,
  },
  {
    caseId: 'CASE-2026-0327-018', title: 'Polygon Config Regression v2.1.4',
    summary: 'Node config regression introduced in v2.1.4 caused state sync failures for 12% of validators.',
    type: 'Config Drift', source: 'Manual', chainSystem: 'Polygon',
    severity: 'low', status: 'normalized', replayStatus: 'missing', doctrineStatus: 'none',
    cveCount: 0, ingestedAt: '2026-03-27T11:00:00Z', updatedAt: '2026-03-27T14:30:00Z',
    tags: ['config', 'validator', 'sync'], confidence: 72,
  },
  {
    caseId: 'CASE-2026-0326-019', title: 'FRAX Keeper Liquidation Miss',
    summary: 'Keeper network congestion caused 18 under-collateralised positions to exceed safe liquidation window.',
    type: 'Keeper Failure', source: 'ImmuneFi', chainSystem: 'Ethereum',
    severity: 'high', status: 'classified', replayStatus: 'pending', doctrineStatus: 'pending',
    cveCount: 1, cveRefs: ['CVE-2026-9100'],
    ingestedAt: '2026-03-26T08:10:00Z', updatedAt: '2026-03-27T09:00:00Z',
    tags: ['keeper', 'liquidation', 'congestion'], confidence: 87,
  },
  {
    caseId: 'CASE-2026-0325-020', title: 'DAI Depeg Micro-Cascade',
    summary: 'DAI deviated 0.8% from peg during PSM imbalance; arbitrage bots restored peg within 4h.',
    type: 'Stablecoin Depeg', source: 'Research', chainSystem: 'Ethereum',
    severity: 'medium', status: 'doctrine_tagged', replayStatus: 'passed', doctrineStatus: 'linked',
    cveCount: 1, cveRefs: ['CVE-2026-9000'],
    ingestedAt: '2026-03-25T16:55:00Z', updatedAt: '2026-03-28T12:10:00Z',
    tags: ['stablecoin', 'PSM', 'arbitrage'], confidence: 90,
  },
  {
    caseId: 'CASE-2026-0324-021', title: 'WBTC Bridge Signature Bypass',
    summary: 'Multi-sig threshold bypass via signature malleability allowed attacker to approve unauthorised WBTC mint.',
    type: 'Bridge Exploit', source: 'SlowMist', chainSystem: 'Multi',
    severity: 'critical', status: 'verified', replayStatus: 'passed', doctrineStatus: 'updated',
    cveCount: 4, cveRefs: ['CVE-2026-8901', 'CVE-2026-8902', 'CVE-2026-8903', 'CVE-2026-8904'],
    ingestedAt: '2026-03-24T09:20:00Z', updatedAt: '2026-03-29T14:00:00Z',
    tags: ['multi-sig', 'signature', 'WBTC'], confidence: 99,
  },
  {
    caseId: 'CASE-2026-0323-022', title: 'Compound V3 Interest Rate Overflow',
    summary: 'Unsigned integer overflow in interest rate model caused borrowing rate to wrap to 0 for 3 blocks.',
    type: 'Contract Invariant', source: 'ImmuneFi', chainSystem: 'Ethereum',
    severity: 'high', status: 'replay_ready', replayStatus: 'available', doctrineStatus: 'pending',
    cveCount: 2, cveRefs: ['CVE-2026-8800', 'CVE-2026-8801'],
    ingestedAt: '2026-03-23T14:40:00Z', updatedAt: '2026-03-25T10:00:00Z',
    tags: ['overflow', 'interest-rate', 'lending'], confidence: 95,
  },
  {
    caseId: 'CASE-2026-0322-023', title: 'Avalanche RPC Degradation Event',
    summary: 'RPC layer overload caused 40% of public nodes to return stale state; wallets showed incorrect balances.',
    type: 'Chain Halt', source: 'Manual', chainSystem: 'Avalanche',
    severity: 'low', status: 'ingested', replayStatus: 'missing', doctrineStatus: 'none',
    cveCount: 0, ingestedAt: '2026-03-22T22:00:00Z', updatedAt: '2026-03-22T22:00:00Z',
    tags: ['RPC', 'node', 'degradation'], confidence: 65,
  },
  {
    caseId: 'CASE-2026-0321-024', title: 'MEV Bot Flash Loan Drain — Aave',
    summary: 'Coordinated MEV bots used flash loans to capture $8.2M via multi-pool arbitrage during low-liquidity window.',
    type: 'MEV Attack', source: 'Research', chainSystem: 'Ethereum',
    severity: 'high', status: 'classified', replayStatus: 'pending', doctrineStatus: 'none',
    cveCount: 0, ingestedAt: '2026-03-21T13:30:00Z', updatedAt: '2026-03-22T08:00:00Z',
    tags: ['MEV', 'flash-loan', 'arbitrage'], confidence: 83,
  },
  {
    caseId: 'CASE-2026-0320-025', title: 'SWIFT Settlement Disruption Model',
    summary: 'Research model simulating SWIFT network partition effect on DeFi protocol treasury exposure.',
    type: 'Settlement Failure', source: 'Research', chainSystem: 'TradFi',
    severity: 'medium', status: 'normalized', replayStatus: 'missing', doctrineStatus: 'pending',
    cveCount: 0, ingestedAt: '2026-03-20T10:00:00Z', updatedAt: '2026-03-21T09:30:00Z',
    tags: ['tradfi', 'simulation', 'SWIFT'], confidence: 70,
  },
  {
    caseId: 'CASE-2026-0319-026', title: 'Hop Protocol Keeper Stall',
    summary: 'Keeper relay stalled on Arbitrum side of Hop bridge during gas spike; pending bonded transfers expired.',
    type: 'Keeper Failure', source: 'ImmuneFi', chainSystem: 'Arbitrum',
    severity: 'medium', status: 'doctrine_tagged', replayStatus: 'passed', doctrineStatus: 'linked',
    cveCount: 1, cveRefs: ['CVE-2026-8700'],
    ingestedAt: '2026-03-19T07:15:00Z', updatedAt: '2026-03-21T15:20:00Z',
    tags: ['keeper', 'bridge', 'gas-spike'], confidence: 92,
  },
  {
    caseId: 'CASE-2026-0318-027', title: 'Uniswap V4 Admin Role Escalation',
    summary: 'Permissioned pool hook contained admin escalation path allowing fee parameter modification without governance approval.',
    type: 'Admin Compromise', source: 'SlowMist', chainSystem: 'Ethereum',
    severity: 'critical', status: 'needs_review', replayStatus: 'missing', doctrineStatus: 'none',
    cveCount: 2, cveRefs: ['CVE-2026-8601', 'CVE-2026-8602'],
    ingestedAt: '2026-03-18T18:40:00Z', updatedAt: '2026-03-18T18:40:00Z',
    tags: ['admin', 'hook', 'fee-manipulation'], confidence: 77,
  },
  {
    caseId: 'CASE-2026-0317-028', title: 'Pyth Oracle Deviation — SOL/USD',
    summary: 'Pyth confidence interval exceeded threshold during market volatility; dependent protocol auto-paused for 22min.',
    type: 'Oracle Manipulation', source: 'Manual', chainSystem: 'Solana',
    severity: 'high', status: 'verified', replayStatus: 'passed', doctrineStatus: 'updated',
    cveCount: 1, cveRefs: ['CVE-2026-8500'],
    ingestedAt: '2026-03-17T11:50:00Z', updatedAt: '2026-03-20T13:00:00Z',
    tags: ['oracle', 'pyth', 'confidence-interval'], confidence: 96,
  },
];

// ─── Summary stats ────────────────────────────────────────────────────────────

export const MOCK_SUMMARY_STATS: CaseLibrarySummaryStats = {
  activeRecords:            28,
  activeRecordsDelta:       6,
  newCvesAdded:             12,
  healthStatus:             'healthy',
  pipelineHealth:           'healthy',
  libraryMaturity:          'enriched',
  normalizationSuccessRate: 100,
  syncUptimePct:            99.8,
  pendingActions:           14,
  pendingReplayCount:       6,
  pendingDoctrineCount:     6,
  pendingReviewCount:       2,
  failedIngestionCount:     0,
  replayCoveragePct:        57,
  doctrineLinkedPct:        54,
  failedIngestions:         2,
  lastSyncAt:               '2026-04-25T09:41:00Z',
};

// ─── Activity feed ────────────────────────────────────────────────────────────

export const MOCK_ACTIVITY: CaseLibraryActivityItem[] = [
  { id: 'a1',  timestamp: '2026-04-25T09:41:00Z', category: 'ingest',     severity: 'info',     message: '12 new CVEs ingested from NVD feed — 3 critical, 5 high' },
  { id: 'a2',  timestamp: '2026-04-25T09:38:00Z', category: 'doctrine',   severity: 'info',     message: 'CASE-2026-0412-001 validation passed — doctrine linkage confirmed' },
  { id: 'a3',  timestamp: '2026-04-25T09:22:00Z', category: 'replay',     severity: 'info',     message: 'Replay generated for Oracle Deviation Event (CASE-2026-0411-002)' },
  { id: 'a4',  timestamp: '2026-04-25T09:10:00Z', category: 'doctrine',   severity: 'info',     message: 'Doctrine tag applied: Oracle Fallback Required — 3 cases updated' },
  { id: 'a5',  timestamp: '2026-04-25T08:55:00Z', category: 'error',      severity: 'high',     message: '2 records failed normalization — queued for manual review' },
  { id: 'a6',  timestamp: '2026-04-25T08:40:00Z', category: 'ingest',     severity: 'info',     message: 'SlowMist source sync completed — 8 new records ingested' },
  { id: 'a7',  timestamp: '2026-04-25T08:15:00Z', category: 'escalation', severity: 'critical', message: 'Critical governance exploit escalated to priority review queue' },
  { id: 'a8',  timestamp: '2026-04-25T07:50:00Z', category: 'ingest',     severity: 'info',     message: 'ImmuneFi feed synchronized — 14 records updated, 2 new' },
  { id: 'a9',  timestamp: '2026-04-25T07:30:00Z', category: 'normalize',  severity: 'info',     message: 'CASE-2026-0408-005 classified — Treasury Imbalance confirmed' },
  { id: 'a10', timestamp: '2026-04-25T06:55:00Z', category: 'ingest',     severity: 'info',     message: 'Daily ingestion pipeline started — 3 sources active, 0 errors' },
];

// ─── Metrics ──────────────────────────────────────────────────────────────────

export const MOCK_METRICS: CaseLibraryMetrics = {
  sourceBreakdown: [
    { source: 'SlowMist',  count: 9,  color: '#F97316' },
    { source: 'ImmuneFi',  count: 8,  color: '#3B82F6' },
    { source: 'Manual',    count: 6,  color: '#8B5CF6' },
    { source: 'Research',  count: 5,  color: '#D4AF37' },
  ],
  severityDistribution: [
    { severity: 'critical', count: 9 },
    { severity: 'high',     count: 11 },
    { severity: 'medium',   count: 6 },
    { severity: 'low',      count: 2 },
  ],
  replayStats: {
    available:   7,
    missing:     7,
    passed:      9,
    failed:      2,
    pending:     3,
    coveragePct: 57,
  },
  doctrineStats: {
    linked:     11,
    updated:    4,
    pending:    8,
    none:       5,
    linkedPct:  54,
  },
  ingestionStats: {
    rawIngestsToday:   34,
    normalizedToday:   32,
    failedIngestions:  2,
    pendingReview:     4,
    avgProcessTimeSec: 1.4,
    lastSyncAt:        '2026-04-25T09:41:00Z',
  },
};
